name: servizio_x
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/images/

#splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: lib/core/assets/images/splash_screen.png

  android_12:
    color: "#FFFFFF"
    image: lib/core/assets/images/splash_screen.png
